import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
    {
    id: "9nHHMBHUj04",
    video_title: "Course promo edit",
    video_description: `The best editing technic in the film editing`,
//     tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "9nHHMBHUj04",
    client_image: "/companies/sl-logo.png",
//     client_feedback: "",
    video_link: "https://youtu.be/9nHHMBHUj04",
//     project_images: [],
    category: ["Promo", "long form",],
//     duration: "6:32",
    software_used: ["DaVinci Resolve"],
  },




  {
    id: "-p95zvooNeU",
    video_title: "Short edit:1(Kuleshov effect)",
    video_description: `The best editing technic in the film editing`,
//     tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "-p95zvooNeU",
    client_image: "/companies/sl-logo.png",
//     client_feedback: "",
    video_link: "https://youtube.com/shorts/-p95zvooNeU",
//     project_images: [],
    category: ["Talking Head", "Shorts","Explainer"],
//     duration: "6:32",
    software_used: ["DaVinci Resolve"],
  },
  {
    id: "p1jOAlF8oyY",
    video_title: "Short edit:2(Font family)",
    video_description: `Font family is the most important thing in design`,
//     tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "p1jOAlF8oyY",
    client_image: "/companies/sl-logo.png",
//     client_feedback: "",
    video_link: "https://youtube.com/shorts/p1jOAlF8oyY",
//     project_images: [],
    category: ["Talking Head", "Shorts","Explainer"],
//     duration: "6:32",
    software_used: ["DaVinci Resolve"],
  },
  {
    id: "bA27oBSGi8c",
    video_title: "Short edit:3(Typography)",
    video_description: `Most editor make one big mistake..`,
//     tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "bA27oBSGi8c",
    client_image: "/companies/sl-logo.png",
//     client_feedback: "",
    video_link: "https://youtube.com/shorts/bA27oBSGi8c?feature=share",
//     project_images: [],
    category: ["Talking Head", "Shorts","Explainer"],
//     duration: "6:32",
    software_used: ["DaVinci Resolve"],
  },
  {
    id: "aiudSt8yCpU",
    video_title: "Short edit:4(Secret of empolyment)",
    video_description: `5 tricks to get hired`,
//     tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "aiudSt8yCpU",
    client_image: "/companies/sl-logo.png",
//     client_feedback: "",
    video_link: "https://youtube.com/shorts/aiudSt8yCpU?feature=share",
//     project_images: [],
    category: ["Talking Head", "Shorts","Explainer"],
//     duration: "6:32",
    software_used: ["DaVinci Resolve"],
  },
  {
    id: "PCk_Xi1PFmM",
    video_title: "Short edit:5",
    video_description: ``,
//     tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "PCk_Xi1PFmM",
    client_image: "/companies/sl-logo.png",
//     client_feedback: "",
    video_link: "https://youtube.com/shorts/PCk_Xi1PFmM?feature=share",
//     project_images: [],
    category: ["Talking Head", "Shorts","Explainer"],
//     duration: "6:32",
    software_used: ["DaVinci Resolve"],
  },

  {
    id: "O0r1DWbTOCs",
    video_title: "Short edit:6",
    video_description: ``,
//     tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "O0r1DWbTOCs",
    client_image: "/companies/sl-logo.png",
//     client_feedback: "",
    video_link: "https://youtube.com/shorts/O0r1DWbTOCs?feature=share",
//     project_images: [],
    category: ["Talking Head", "Shorts","Explainer"],
//     duration: "6:32",
    software_used: ["DaVinci Resolve"],
  },
  {
    id: "VWjkvLu5MTM",
    video_title: "Short edit:7",
    video_description: ``,
//     tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "VWjkvLu5MTM",
    client_image: "/companies/sl-logo.png",
//     client_feedback: "",
    video_link: "https://youtube.com/shorts/VWjkvLu5MTM?feature=share",
//     project_images: [],
    category: ["Talking Head", "Shorts","Explainer"],
//     duration: "6:32",
    software_used: ["DaVinci Resolve"],
  },
  {
    id: "j4Lmm5pycnU",
    video_title: "Short edit:8",
    video_description: ``,
//     tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "j4Lmm5pycnU",
    client_image: "/companies/sl-logo.png",
//     client_feedback: "",
    video_link: "https://youtube.com/shorts/j4Lmm5pycnU?feature=share",
//     project_images: [],
    category: ["Talking Head", "Shorts","Explainer"],
//     duration: "6:32",
    software_used: ["DaVinci Resolve"],
  },
  {
    id: "_rhfosi6wY0",
    video_title: "Short edit:9",
    video_description: ``,
//     tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "_rhfosi6wY0",
    client_image: "/companies/sl-logo.png",
//     client_feedback: "",
    video_link: "https://youtube.com/shorts/_rhfosi6wY0?feature=share",
//     project_images: [],
    category: ["Talking Head", "Shorts","Explainer"],
//     duration: "6:32",
    software_used: ["DaVinci Resolve"],
  },
  {
    id: "0jccjGmSBZs",
    video_title: "Drama editing",
    video_description: ``,
//     tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "0jccjGmSBZs",
    client_image: "/companies/sl-logo.png",
//     client_feedback: "",
    video_link: "hhttps://youtu.be/0jccjGmSBZs",
//     project_images: [],
    category: ["Film edit"],
//     duration: "6:32",
    software_used: ["DaVinci Resolve"],
  },

]