import { VideoProject } from "@/types/videos";

export const allVideoProjects: VideoProject[] = [
        {
    id: "hjUi9vvuTFM",
    video_title: "Short form",
    video_description: `short-form edit with clean cuts ,motion graphics and captions, designed to improve viewer retention on social media.`,
    tags: [""],
    cover_image: "hjUi9vvuTFM",
    client_image: "/hasiblogo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/hjUi9vvuTFM",
    project_images: [],
    category: ["Talking Head", "Shorts"],
    duration: "",
    software_used: ["DaVinci Resolve"],
    client_name: "",
    publish_date: "",
  },
  {
    id: "bA27oBSGi8c",
    video_title: "Short form ",
    video_description: `Smooth animation and strong hook to grab attention of user.`,
     tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "bA27oBSGi8c",
    client_image: "/hasiblogo.png",
     client_feedback: "",
    video_link: "https://youtube.com/shorts/bA27oBSGi8c?feature=share",
    project_images: [],
    category: ["Talking Head", "Shorts"],
     duration: "",
    software_used: ["DaVinci Resolve"],
      client_name: "",
    publish_date: "",
  },

  {
    id: "-p95zvooNeU",
    video_title: "Short form",
    video_description: ` pacing and visual flow to keep viewers engaged throughout the video.`,
    tags: [""],
    cover_image: "-p95zvooNeU",
    client_image: "/hasiblogo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/-p95zvooNeU",
    project_images: [],
    category: ["Talking Head", "Shorts"],
     duration: "",
    software_used: ["DaVinci Resolve"],
      client_name: "",
    publish_date: "",
  },
  {
    id: "p1jOAlF8oyY",
    video_title: "Short form",
    video_description: ``,
     tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "p1jOAlF8oyY",
    client_image: "/hasiblogo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/p1jOAlF8oyY",
     project_images: [],
    category: ["Talking Head", "Shorts"],
    duration: "",
    software_used: ["DaVinci Resolve"],
      client_name: "",
    publish_date: "",
  },

    {
    id: "9nHHMBHUj04",
    video_title: "Course promo edit",
    video_description: ``,
    tags: [""],
    cover_image: "9nHHMBHUj04",
    client_image: "/hasiblogo.png",
    client_feedback: "",
    video_link: "https://youtu.be/9nHHMBHUj04",
    project_images: [],
    category: ["Promo"],
    duration: "",
    software_used: ["DaVinci Resolve"],
    client_name: "",
    publish_date: "",
  },


  {
    id: "aiudSt8yCpU",
    video_title: "Short form",
    video_description: ``,
     tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "aiudSt8yCpU",
    client_image: "/hasiblogo.png",
    client_feedback: "",
    video_link: "https://youtube.com/shorts/aiudSt8yCpU?feature=share",
     project_images: [],
    category: ["Talking Head", "Shorts"],
     duration: "",
    software_used: ["DaVinci Resolve"],
      client_name: "",
    publish_date: "",

  },
    {
    id: "0jccjGmSBZs",
    video_title: "Drama editing",
    video_description: `Film editing tricks and sound design to feel the viewer something in depth.`,
     tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "0jccjGmSBZs",
    client_image: "/hasiblogo.png",
     client_feedback: "",
    video_link: "hhttps://youtu.be/0jccjGmSBZs",
     project_images: [],
    category: ["Film edit"],
     duration: "",
    software_used: ["DaVinci Resolve"],
      client_name: "",
    publish_date: "",
  },

//   {
//     id: "PCk_Xi1PFmM",
//     video_title: "Short edit",
//     video_description: ``,
//     tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
//     cover_image: "PCk_Xi1PFmM",
//     client_image: "/hasiblogo.png",
//      client_feedback: "",
//     video_link: "https://youtube.com/shorts/PCk_Xi1PFmM?feature=share",
//     project_images: [],
//     category: ["Talking Head", "Shorts"],
//      duration: "",
//     software_used: ["DaVinci Resolve"],
//       client_name: "",
//     publish_date: "",
//   },

  {
    id: "O0r1DWbTOCs",
    video_title: "Short form",
    video_description: ``,
     tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "O0r1DWbTOCs",
    client_image: "/hasiblogo.png",
     client_feedback: "",
    video_link: "https://youtube.com/shorts/O0r1DWbTOCs?feature=share",
     project_images: [],
    category: ["Talking Head", "Shorts"],
     duration: "",
    software_used: ["DaVinci Resolve"],
      client_name: "",
    publish_date: "",
  },
//   {
//     id: "VWjkvLu5MTM",
//     video_title: "Short edit",
//     video_description: ``,
//      tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
//     cover_image: "VWjkvLu5MTM",
//     client_image: "/hasiblogo.png",
//      client_feedback: "",
//     video_link: "https://youtube.com/shorts/VWjkvLu5MTM?feature=share",
//      project_images: [],
//     category: ["Talking Head", "Shorts"],
//     duration: "",
//     software_used: ["DaVinci Resolve"],
//       client_name: "",
//     publish_date: "",
//   },
  {
    id: "j4Lmm5pycnU",
    video_title: "Short form",
    video_description: ``,
     tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "j4Lmm5pycnU",
    client_image: "/hasiblogo.png",
     client_feedback: "",
    video_link: "https://youtube.com/shorts/j4Lmm5pycnU?feature=share",
     project_images: [],
    category: ["Talking Head", "Shorts"],
     duration: "",
    software_used: ["DaVinci Resolve"],
      client_name: "",
    publish_date: "",
  },
  {
    id: "_rhfosi6wY0",
    video_title: "Short form",
    video_description: ``,
     tags: ["Resume Tips", "FAANG Career", "Job Preparation", "Career Advice"],
    cover_image: "_rhfosi6wY0",
    client_image: "/hasiblogo.png",
     client_feedback: "",
    video_link: "https://youtube.com/shorts/_rhfosi6wY0?feature=share",
    project_images: [],
    category: ["Talking Head", "Shorts"],
     duration: "",
    software_used: ["DaVinci Resolve"],
      client_name: "",
    publish_date: "",
  },

]